### ISSUE TITLE
文档样式严重影响组件样式

### ISSUE THREAD

**Issue by bougieL** [XiaoMi/hiui#234]
所有用了 `ul` `li` 标签的组件必须用 `! important` 来清除文档样式的影响 :expressionless:

**Comment by sivan** [comment]
在组件根级引入 `@include component-reset();` 即可。

``` scss
.hi-dropdown {
  position: relative;
  user-select: none;
  max-width: 200px;

  @include component-reset();

  // ...
}
```

**Comment by bougieL** [comment]
主要是 `ul` 和 `ol` 被影响了，这个 `reset` 没有 reset `ul` 和 `ol` 的 `padding` 和 `margin`

![VPGevF.png](https://s2.ax1x.com/2019/05/23/VPGevF.png)

![VPGwVA.png](https://s2.ax1x.com/2019/05/23/VPGwVA.png)

**Comment by sivan** [comment]
`component-reset()` 有对子元素进行 `ul, ol` 的样式重置啊。不建议采用全局 ul, ol 样式重置，会让两个元素失去本来的样式。未来通过 hiui-core-css 升级来妥善修复此问题。

**Comment by bougieL** [comment]
```scss
@mixin component-reset() {
  font: normal #{$font-size-normal}/#{$line-height-default} $font-family-base;
  text-align: left;
  text-indent: 0;
  text-shadow: none;
  text-transform: none;
  letter-spacing: 0;
  word-spacing: normal;
  white-space: normal;
  color: $black;

  ul,
  ol {
    margin: 0;
    padding: 0;
    list-style-type: none;
  }

  dl {
    margin-top: 0;
    margin-bottom: 0;
  }

  li + li {
    margin: 0;
  }

  a {
    padding-left: 0;
    padding-right: 0;
  }
}
```

这个是重置了 `margin` 和 `padding`，但是文档写的是 `margin-top`、`margin-bottom`、`padding-left` 等等，重置没有效果啊 :thinking:
